dkdlelk99/CSOS-Algorithm

- BOJ/1085/dkdlelk99.py
- BOJ/4153/dkdlelk99.py
그냥 fork뜬 레포에 알고리즘 푼 거 올리고 PR만 날리면 됨
1. 로컬 저장소에 remote 저장소 가져오기 `git clone <url.git>`
2. `git branch <새로운 브랜치 이름>` 으로 브랜치 생성
3. `git checkout <아까 만든 브랜치 이름>`으로 새로 만든 브랜치로 넘어온다.
3. 로컬 GUI 켜서 작업 (dir 생성, .py 파일 추가 ... )
4. `git add` - 자세 잡기,  `git commit` - 사진 찍기 로 상태 저장
5. `git push <리모트 저장소 이름> <푸시할 브랜치 이름>` 으로 온라인에 내 로컬 저장소의 상태를 push
6. 브랜치가 생기고 3에서 작업한 변경 사항을 main 브랜치로 PR을 날린다.
여러분은 새로운 브랜치를 만들 필요 없이 개개인이 포크한 저장소에서 main으로 PR을 날리면 됨!
> 새로운 브랜치 생성, 새로운 브랜치에서 main으로 PR (오늘은 연습용, 아무 댓글이나 남겨주세요)

- 개팬다/README.md
> 개팬다 README.md 추가

- BOJ/2775/README.md
- BOJ/2775/dkdlelk99.py
- BOJ/2798/README.txt
- BOJ/2798/dkdlelk99.py
* 블랙잭
`M을 넘지 않으면서 M에 최대한 가까운`조건을 안읽고 더 어렵게 풀고 있었다.
`abs()`를 쓰면 `M을 넘지 않으면서`라는 조건을 빼고도 만족시킬 수 있다.
* 부녀회장이 될테야
문제에 중딩 때 쎈에서나 보던 어거지 스토리 안넣었으면 좋겠다.
문제 자체는 좋음
> 블랙잭, 부녀회장이 될테야

- BOJ/11050/README.md
- BOJ/11050/dkdlelk99.py
- BOJ/1259/README.md
- BOJ/1259/dkdlelk99.py
브론즈 1보다 브론즈 2가 더 어려웠다.
solved.ac 하위 클래스는 난이도 믿을게 못되는 듯?
나도 빨리 빡고수가 되고싶다
> 이항 계수1, 팰린드롬수

- BOJ/11650/README.md
- BOJ/11650/dkdlelk99.py
- BOJ/2751/README.md
- BOJ/2751/dkdlelk99.py
같은 난이도의 정렬 문제는 하나만 잘 풀어도 나머지가 슝슝 풀려서 달달했다.
> 좌표 정렬하기, 수 정렬하기 2

- 개팬다/HEEA/BOJ_1920.py
범위가 거듭제곱이기 때문에 엄청나게 많음 그런데 거기서 배열을 여러개 쓰다보니 배열의 거듭제곱이 됨
따라서 메모리 부족 현상 발생...
시간초과 해결하기 위해 인덱스로 원소 접근했더니 메모리 부족 문제라니... 좀 더 해결해보겠음,,,
> 시간초과 해결하니 메모리 초과, 리스트를 줄일 방법을 찾아보겠음

- 개팬다/HEEA/BOJ_1654.py
> 풀긴 했는데 풀이에 있어 만족스럽지 않음 고로 아직 보류

- 개팬다/HEEA/BOJ_2805.py
> 정답이긴 한데 풀면서도 애매 ㅜ 잠시만요 고민좀요 ㅜ

- BOJ/10950/ghwns82.py
- BOJ/14681/ghwns82.py
- BOJ/2739/ghwns82.py
- BOJ/2884/ghwns82.py
- BOJ/8393/README.md
- BOJ/8393/ghwns82.py
> 08.04 일자 문제풀이

- BOJ/11723/README.md
- BOJ/11723/dkdlelk99.py
> [11723 집합] 오랜만에 PS

- BOJ/10951/ghwns82.py
- BOJ/10952/ghwns82.py
- BOJ/1110/ghwns82.py
이번에 푼 문제가 해인이가 8일 전에 푼거였음...
해인이 기다려 곧 따라갈게
> 08.10 일자 코딩

- BOJ/1620/README.md
- BOJ/1620/dkdlelk99.py
문제 설명이 중학교 쎈 실생활 문제처럼 너무 주절주절거림
다 무시하고 내려서 입력 부분부터 읽어도 됨
ps.
파이썬 dict 너무 사기다
> [1620 나는야 포켓몬 마스터 이다솜] 

- 개팬다/HEEA/BOJ_11279.py
우선순위 큐 개념이 필요할 것 같은데 까먹었음..... 공부좀 해서 다시 풀어봐야겠어..
> 이 부분은 공부좀 해보겠음

- BOJ/1620/HEEA.py
- BOJ/1764/HEEA.py
- BOJ/2920/HEEA.py
- BOJ/2920/README.md
그래도 나름 실버로 풀고 있고 문제도 2~3문제 풀고있어영,,, 1,2문제 차이로 class를 다 못채우면 아쉬워..
> class 모자란것들 1, 2문제 채우기

- 개팬다/HEEA/BOJ_1064.py
음.. 반례들 다 잡아낸것 같은데 아직도 계속 틀렸다고 나오네... 고민좀 해볼게요 뭔가 풀릴듯 말듯이네
> 어디가 틀린지 모르겠다..

- BOJ/17219/HEEA.py
- BOJ/17219/README.md
딕셔너리 사용하면 리스트의 탐색함수보다 시간복잡도가 작아요~~
> 딕셔너리 이용 문제 요즘 많이 보이는 것 같다?..

- BOJ/1927/HEEA.py
> 파이썬 모듈은 신이다.

- 개팬다/dkdlelk99/1697/README.md
- 개팬다/dkdlelk99/1697/dkdlelk99.py
분명히 접근은 잘 한거같은데 런타임 에러랑 반례`0 100000` 왜 틀리는지 모르겠따,,,,
100,000 너무 커서 디버깅이 좀 어려운데 파이썬 디버거 좀 잘 쓰는 사람?
특정 루프까지 돌릴 수 있는 방법 있는지 궁금해요.
ex) `for i in range(100000)` 같은거 있으면 `i == 9999` 일 때 break같은게 가능한가?
> [1697 숨바꼭질] 너비 우선 탐색 DFS문제 실패

- 개팬다/dkdlelk99/1260/README.md
- 개팬다/dkdlelk99/1260/dkdlelk99.py
기대하던 게임 나와서 너무 집중 안됨
집가서 나 겜해야겠음
내일 다시 도전한다
> [1260] DFS BFS 실패

- BOJ/1065/dkdlelk99.py
집에 있으면 공부하기 너무 시러 😫 
그래서 날로 하나 후루룩함
> 음메 집에서 겜하다가 또 까먹을 뻔 했내오,,,.,

- BOJ/2231/ghwns82.py
- BOJ/7568/README.md
- BOJ/7568/ghwns82.py
> 09.10 혼미한 정신속 문제풀이 

- 개팬다/dkdlelk99/7662/README.md
- 개팬다/dkdlelk99/7662/dkdlelk99.py
간단하게 생각하고 큐 두개 만들었는데 실패했다.
다시 처음부터 잘 만들어봐야되려나..
> [이중 우선순위 큐]

- 개팬다/dkdlelk99/17626/README.md
- 개팬다/dkdlelk99/17626/dkdlelk99.py
> [Four Squares 17626] fail,.,.,.

- 개팬다/dkdlelk99/1260/retry.py
좀만 더하면 풀릴거같음
이게 다 집 데스크 탑에 파이참 깔기가 귀찮아가지고 메모장으로 코딩해서 그럼
내일 저녁에 연구실에서 좀만 손보면 맞출거가틈
> [DFS와 BFS] 2차 도전 실패함

- 개팬다/dkdlelk99/17626/answer.py
brute force지롱
결국 못풀어서 답봄
그리고 목요일에 알고리즘 풀기 너무 빡셉니다 😭 
아무도 안물안궁인목요일 일과
기상 8:30
학교 10:30
강의 찔끔, 점심 12:30
연구 16:00
실강 17:30
알바 19:00
집 22:00
집오면 하기 싫어 어뜩하지
> [four squares 17626] dp인줄 알았냐

- BOJ/11653/dkdlelk99.py
다음주만 또 버티면 그다음주부터는 일주일에 하루씩 대체공휴일!
요즘 빨간날만 보고산다 ㄹㅇ
> [11653 소인수분해] 좋은 주말~~~~

- BOJ/1074/REDME.md
- BOJ/1074/dkdlelk99.py
인줄 알았냐?
수학문제지롱~
2~3주전에 도전하고 실패한 문제인데 다시 도전해서 맞춤
나는 짱
기분 째진다
분할 정복으로도 풀 수 있을거같긴하니까 다음 타자는 분할 정복으로 풀어주세요
> [Z 1074] 분할정복

- BOJ/1260/README.md
- BOJ/1260/dkdlelk99.py
- 개팬다/dkdlelk99/1260/dkdlelk99_last_ver.py
나는 12일 전의 나보다 강하다 후하하
그리고 class3 찍으니까 뽀나쓰로 50점 줘가지고 실2 달성
에센셜 4문제만 더 맞추면 실1 가겠다 힣
> [DFS와 BFS 1260] 리트라이 성공~!

- BOJ/2407/README.md
- BOJ/2407/dkdlelk99.py
파스칼 삼각형을 이용 -> 곱셈 연산 없음
메모리 500메가나 줘서 충분함
만약에 메모리를 20메가로 제한해도 삼각형의 대칭을 이용해서 공간 절반 날리면 충분히 품
> [2407 조합] 큰 수로 가면 생각할게 은근히 많은 combination

- BOJ/1026/dkdlelk99.py
순위를 매겨서 알고리즘을 해결해야하는 것 처럼 보였는데..
두 리스트 다 소팅시켜도 시간 잘 나와서 걍 품 ㅎㅎ 날먹 달달해
> [1026 보물] 11/01 daily algorithm

- 개팬다/dkdlelk99/1697/dkdlelk99_2.py
이번엔 BFS를 깔끔하게 구현하는데까지는 성공,
but,, depth를 어떻게 재야할지 모르겠음..
> [1697 숨바꼭질] 리트 Fail

- BOJ/1697/README.md
- BOJ/1697/dkdlelk99.py
구글링해서 품
depth를 처리할 땐 그냥 리스트 하나 통으로 만들자
공간 낭비라고 생각했는데 다른 방법 없으면 이거부터 생각하자
> [1697 숨바꼭질] 굴복함

- BOJ/17140/README.md
- BOJ/17140/hikang.py
> 1109 이차원 배열과 연산

- BOJ/15652/dkdlelk99.py
> 11/11 [15652 N과M (4)] 하나 풀어두니까 날먹 가능~~

- BOJ/15654/dkdlelk99.py
5시 반 이후로 일정이 있어서 피치 못하게 좀 일찍 pr을 날립니다..
> 11/12 [15645 N과 M (5)] 또 조합 문제

- BOJ/15657/dkdlelk99.py
> 11/15 [15657 N과 M (8)] 백트레킹, 재귀에 대한 이해

- BOJ/1000/dbql99.py
> [1000] 2.4 test

- BOJ/2557/dbql99.py
> 2.7 , 2557

- BOJ/10869/JungJeeheun.c
- BOJ/2920/JungJeeheun.c
> 2월 7일, 문제: [2920]

- BOJ/10989/dkdlelk99.py
> 0208, [10989] 2일차는 날먹

- BOJ/1085/dbql99.py
- BOJ/4153/dbql99.py
> 02.08 - 1085

- BOJ/4153/new_dbql99.py
> 02-09 / 4153 

- 개팬다/dkdlelk99/1316/README.md
- 개팬다/dkdlelk99/1316/dkdlelk99.py
> [1316] 그룹 단어 체커 fail (0207)

- BOJ/1427/dkdlelk99.py
> [1427] 0209 소트인사이드

- BOJ/10250/dbql99.py
이번 문제는 수학적인 규칙만 찾으면 해결했음! 하지만, 그 과정이 순탄치 않았음...
특히 문제가 길면, 읽기 귀찮고,,,하기 싫어지고,,, 이렇게 긴 문제는 처음으로 푼듯! 뿌듯쓰
> 02-10 / 10250 

- 개팬다/dbql99/2231
처음으로 막힌 문제가 등장... 오늘은 세미나와 본가 온다고, 풀이법을 더 자세히 보지 못했음. 월요일에 알고리즘 책으로 '무식하게 풀기' 방법 공부하고, 다시 풀어보도록 하겠음.
> 2/11 - 2231

- BOJ/1934/dkdlelk99.py
너무 날먹인데 힣
스트레스 이빠이 받은 날이라 좀 봐주소
> [1934] 0211 최소공배수

- BOJ/2231/dbql99.py
느낀 점
1. 파이썬에서 map함수를 좀 잘써먹어야 할듯... 이거 몰라서, 하나씩 다 대입해서 수학적으로 풀려고 하였음.
2. '무식하게 푸는 법'
3. 중간에 주석으로 해둔 부분부터, 들여쓰기와 break 등으로 출력을 자유자재로 할 수 있다는 점을 깨달음
4. 주석으로 해둔 부분부터 리뷰 요청.
> 2.14 / 2231

- BOJ/1181/JungJeeheun.c(못품)
> [1181] 0214

- BOJ/1316/dkdlelkpp.py
저번에 틀린 문제 찢었다
연결 리스트에서 자주 사용되는 개념인 follower 이용
> [1316] 0214 그룹 단어 체커 복수 성공

- 개팬다/dbql99/2292.py
브론즈4 문제에서 브론즈2 문제를 푸니,,,조금씩 시간이 걸리기 시작한다... 아직 구글링은 하지 않았고,,, 이 문제만큼은 혼자 풀고 싶다는 생각이 듦. 나 도와줄 작호 형이나 우사이 구함
> 02-15/2292

- BOJ/2941/dkdlelk99.py
우리 연구원들이 푼거 봤는데 혼자 풀이 딴판이네 힛
조금 C/C++ 스타일에 가까웠는데 문제 생각하면 이게 옳은 풀이 같?음
파이썬에 너무 길들여진 느낌이야
> [2941] 0215 크로아티아 알파벳

- 개팬다/11650/JungJeeheun.c(못품)
선택정렬 알고리즘으로 풀었는데 합병정렬로 풀어야 시간초과가 나지않는다.. 정렬에대해서 더 공부해야할거같다
> 2/21 11650번 문제 시간초과..

- BOJ/9498/dbql99.py
오늘 밤 늦게 와서,,, 자기 직전까지 까먹고 있다가, 갑자기 생각나서 후다닥 해야됐는데, 너무 귀찮아서 걍 벌금 낼까 하다가, 그래도 쉬운거라도 올려보자 해서 부랴부랴 했다. 근데 너무 쉬운거지만, 했다는거에 의의를 두면서, 자야지
그리고 내일부터 어제 문제가 어렵다고 해서, 우상이랑 작호형이 문제들 추천해줘서 고맙고, 내일부터 하나씩 풀어야겠다!
> 02-17 / 9498

- BOJ/2581/dkdlelk99.py
> [2581] 0216 소수

- BOJ/1541/ghwns82.py
> 2/23 문제풀이  - 1541번

- BOJ/1158/README.md
- BOJ/1158/dkdlelk99.py
- 개팬다/dkdlelk99/1158/README.md
- 개팬다/dkdlelk99/1158/dkdlelk99.py
이 문제 왜 데자뷰가 느껴지지?
분명히 옛날에 본 문제에 풀면서 이렇게 풀면 시간 초과나겠다~ 하면서 풀었는데 그렇게 됐내오?
근데 목요일은 알바가야되니깐 걍 날로 해먹음
+) 못풀어서 개팬다에 올려야되는데 실수로 내 브랜치 BOJ에 올려서 커밋 조금 쌓임
> [1158] 0217 요세푸스 문제 시간 초과

- BOJ/9012/JungJeeheun.c
스택으로 풀수 있는데 한번도 스택으로 풀어본적이 없어서 이렇게 풀었다ㅠㅠ
> 2/24 9012번 실4
